#!/usr/local/bin/bash

source config.sh
source change_analyzer.sh
source patch_checker.sh

#########################################
# Analyze changes in a port before	#
# committing				#
#########################################

analyze_changes "${1}"
print_report
run_linters "${1}"
